[project]
name = "demo-shiny-py-cran-downloads"
version = "0.1.0"
description = "A Shiny for Python app to explore CRAN downloads."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=5.5",
    "duckdb>=1.2.0",
    "plotnine>=0.14.5",
    "shiny>=1.3.0",
]
